// High-Resolution Curated Sacred Indian Pilgrimage & Tour Imagery (100% Verified HTTP 200)
export const voyageImages = {
  hero: "https://images.unsplash.com/photo-1626621341517-bbf3d9990a23?w=1600&auto=format&fit=crop&q=85",
  kedarnath: "https://images.unsplash.com/photo-1626621341517-bbf3d9990a23?w=1200&auto=format&fit=crop&q=85",
  varanasi: "https://images.unsplash.com/photo-1571536802807-30451e3955d8?w=1200&auto=format&fit=crop&q=85",
  jyotirlinga: "https://images.unsplash.com/photo-1582510003544-4d00b7f74220?w=1200&auto=format&fit=crop&q=85",
  ayodhya: "https://images.unsplash.com/photo-1627894483216-2138af692e32?w=1200&auto=format&fit=crop&q=85",
  chardham: "https://images.unsplash.com/photo-1589182373726-e4f658ab50f0?w=1200&auto=format&fit=crop&q=85",
  rishikesh: "https://images.unsplash.com/photo-1544717305-2782549b5136?w=1200&auto=format&fit=crop&q=85",
  rajasthan: "https://images.unsplash.com/photo-1599661046289-e31897846e41?w=1200&auto=format&fit=crop&q=85",
  haridwar: "https://images.unsplash.com/photo-1571536802807-30451e3955d8?w=1200&auto=format&fit=crop&q=85",
  aarti: "https://images.unsplash.com/photo-1609342122563-a43ac8917a3a?w=1200&auto=format&fit=crop&q=85",
  sangam: "https://images.unsplash.com/photo-1514282401047-d79a71a590e8?w=1200&auto=format&fit=crop&q=85",
  goa: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=1200&auto=format&fit=crop&q=85",
  hills: "https://images.unsplash.com/photo-1589182373726-e4f658ab50f0?w=1200&auto=format&fit=crop&q=85",
  kerala: "https://images.unsplash.com/photo-1602216056096-3b40cc0c9944?w=1200&auto=format&fit=crop&q=85",
  meghalaya: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=1200&auto=format&fit=crop&q=85",
  himalaya: "https://images.unsplash.com/photo-1626621341517-bbf3d9990a23?w=1200&auto=format&fit=crop&q=85",
};

export const catalog = [
  {
    id: "kedarnath",
    name: "Kedarnath & Badrinath Dham Yatra",
    location: "Haridwar · Guptkashi · Kedarnath · Badrinath",
    duration: "5 nights · 6 days",
    days: 6,
    price: 18500,
    category: "Pilgrimage",
    image: voyageImages.kedarnath,
    tag: "Most Sacred",
    description: "Sacred Himalayan pilgrimage with VIP temple passes, verified mountain hotels, and pure satvik meals.",
  },
  {
    id: "varanasi",
    name: "Kashi Vishwanath & Ganga Aarti Darshan",
    location: "Varanasi · Sarnath · Prayagraj",
    duration: "3 nights · 4 days",
    days: 4,
    price: 9999,
    category: "Pilgrimage",
    image: voyageImages.varanasi,
    tag: "Divine Aarti",
    description: "Ganga Aarti boat pass at Dashashwamedh Ghat, Kashi Vishwanath VIP Darshan & Sarnath excursion.",
  },
  {
    id: "jyotirlinga",
    name: "12 Jyotirlinga Mahakal & Somnath Tour",
    location: "Ujjain · Omkareshwar · Somnath · Dwarka",
    duration: "6 nights · 7 days",
    days: 7,
    price: 21500,
    category: "Pilgrimage",
    image: voyageImages.jyotirlinga,
    tag: "Mahakal Bhasma",
    description: "Holy Bhasma Aarti booking, AC private vehicle, pure Satvik thali, and dedicated pilgrim coordinator.",
  },
  {
    id: "ayodhya",
    name: "Ayodhya Ram Mandir & Sangam Snan",
    location: "Ayodhya · Prayagraj · Varanasi",
    duration: "4 nights · 5 days",
    days: 5,
    price: 12800,
    category: "Pilgrimage",
    image: voyageImages.ayodhya,
    tag: "Ram Lalla",
    description: "Ram Janmabhoomi Darshan, Hanumangarhi pooja, Triveni Sangam holy dip, and luxury stay.",
  },
  {
    id: "chardham",
    name: "Complete Uttarakhand Char Dham Yatra",
    location: "Yamunotri · Gangotri · Kedarnath · Badrinath",
    duration: "9 nights · 10 days",
    days: 10,
    price: 34999,
    category: "Pilgrimage",
    image: voyageImages.chardham,
    tag: "Four Dhams",
    description: "All 4 holy Dhams covered with verified luxury coaches, medical support & all pooja arrangements.",
  },
  {
    id: "rishikesh",
    name: "Haridwar & Rishikesh Ganga Aarti Tour",
    location: "Haridwar · Rishikesh · Neelkanth",
    duration: "3 nights · 4 days",
    days: 4,
    price: 7999,
    category: "Pilgrimage",
    image: voyageImages.rishikesh,
    tag: "Ganga Darshan",
    description: "Triveni Ghat Ganga Aarti, Ram Jhula & Laxman Jhula sightseeing, and Ganga holy snan pass.",
  },
  {
    id: "rajasthan",
    name: "Rajasthan Heritage & Forts Circuit",
    location: "Jaipur · Jodhpur · Udaipur",
    duration: "7 nights · 8 days",
    days: 8,
    price: 18999,
    category: "Heritage",
    image: voyageImages.rajasthan,
    tag: "Royal Heritage",
    description: "A majestic loop through sandstone palaces, lake palaces of Udaipur, and desert safari camps.",
  },
  {
    id: "goa",
    name: "Goa Coastal Beach & Heritage Holiday",
    location: "North Goa · South Goa · Calangute · Panaji",
    duration: "4 nights · 5 days",
    days: 5,
    price: 14500,
    category: "Beaches",
    image: voyageImages.goa,
    tag: "Beach Holiday",
    description: "Relaxing coastal tour with private AC cab, pristine white beaches, heritage churches, and sunset cruise.",
  },
  {
    id: "kerala",
    name: "Kerala Backwaters & Munnar Hills",
    location: "Kochi · Munnar · Alleppey · Thekkady",
    duration: "5 nights · 6 days",
    days: 6,
    price: 17999,
    category: "Nature",
    image: voyageImages.kerala,
    tag: "Serene Nature",
    description: "Alleppey luxury houseboat cruise, Munnar lush tea gardens, spice plantations & private AC transport.",
  },
];

export const tripStages = ["Booked", "Confirmed", "Documents ready", "On the way"];

export const upcomingTrips = [
  {
    id: "VYG-2026-08456",
    name: "Kedarnath & Badrinath Sacred Yatra",
    dates: "15 Oct – 20 Oct 2026",
    travelers: "2 adults · 1 senior citizen",
    status: "CONFIRMED",
    image: voyageImages.kedarnath,
    progress: 2,
  },
  {
    id: "VYG-2026-08412",
    name: "Kashi Vishwanath & Ganga Aarti",
    dates: "02 Nov – 06 Nov 2026",
    travelers: "2 adults",
    status: "CONFIRMED",
    image: voyageImages.varanasi,
    progress: 1,
  },
];

export const notifications = [
  { id: 1, type: "offer", title: "🚩 Kedarnath 2026 Yatra passes open", body: "VIP Helicopter & Palki darshan registrations active for October batches.", time: "2h ago", unread: true },
  { id: 2, type: "trip", title: "🚩 Your Sacred Yatra itinerary is ready", body: "Open My Trips to download your verified driver & pooja pass details.", time: "Yesterday", unread: true },
  { id: 3, type: "note", title: "🚩 A note from your Har Har Mahadev host", body: "Evening Dashashwamedh Ganga Aarti boat pickup is scheduled at 6:00 PM.", time: "12 Aug", unread: false },
];
