import { and, desc, eq } from "drizzle-orm";
import { z } from "zod";
import { supportChannels, supportTicketReplies, supportTickets } from "../../drizzle/schema";
import { recordAudit } from "../audit/service";
import { getDb } from "../db";
import { protectedProcedure, publicProcedure, router } from "../_core/trpc";
import { assertOwnership, isOperator } from "../security/roles";

const ticketCode = () => `SUP-${new Date().getUTCFullYear()}-${Math.floor(Math.random() * 9000 + 1000)}`;
export const supportRouter = router({
  create: protectedProcedure.input(z.object({ bookingId: z.number().int().positive().optional(), subject: z.string().trim().min(4).max(220), body: z.string().trim().min(10).max(3000) })).mutation(async ({ ctx, input }) => { const db = await getDb(); if (!db) throw new Error("Database unavailable"); const [result] = await db.insert(supportTickets).values({ ticketCode: ticketCode(), userId: ctx.user.id, bookingId: input.bookingId, subject: input.subject, body: input.body }).$returningId(); await recordAudit(ctx.user.id, { eventType: "support.ticket_created", entityType: "support_ticket", entityId: String(result.id) }); return { id: result.id }; }),
  mine: protectedProcedure.query(async ({ ctx }) => { const db = await getDb(); if (!db) return []; return db.select().from(supportTickets).where(eq(supportTickets.userId, ctx.user.id)); }),
  channels: publicProcedure.query(async () => { const db = await getDb(); if (!db) return []; return db.select({ id: supportChannels.id, channel: supportChannels.channel, label: supportChannels.label, destination: supportChannels.destination }).from(supportChannels).where(eq(supportChannels.isActive, true)).orderBy(supportChannels.channel); }),
  thread: protectedProcedure.input(z.object({ ticketId: z.number().int().positive() })).query(async ({ ctx, input }) => { const db = await getDb(); if (!db) return { ticket: null, replies: [] }; const ticket = (await db.select().from(supportTickets).where(eq(supportTickets.id, input.ticketId)).limit(1))[0]; if (!ticket) return { ticket: null, replies: [] }; if (!isOperator(ctx.user.role)) assertOwnership(ctx.user.id, ticket.userId); const replyWhere = isOperator(ctx.user.role) ? eq(supportTicketReplies.ticketId, input.ticketId) : and(eq(supportTicketReplies.ticketId, input.ticketId), eq(supportTicketReplies.visibleToTraveler, true)); const replies = await db.select().from(supportTicketReplies).where(replyWhere).orderBy(supportTicketReplies.createdAt); return { ticket, replies }; }),
  reply: protectedProcedure.input(z.object({ ticketId: z.number().int().positive(), body: z.string().trim().min(2).max(3000) })).mutation(async ({ ctx, input }) => { const db = await getDb(); if (!db) throw new Error("Database unavailable"); const ticket = (await db.select().from(supportTickets).where(eq(supportTickets.id, input.ticketId)).limit(1))[0]; if (!ticket) throw new Error("Support request not found"); assertOwnership(ctx.user.id, ticket.userId); const [created] = await db.insert(supportTicketReplies).values({ ticketId: input.ticketId, authorUserId: ctx.user.id, body: input.body, visibleToTraveler: true }).$returningId(); await db.update(supportTickets).set({ status: "open" }).where(eq(supportTickets.id, input.ticketId)); await recordAudit(ctx.user.id, { eventType: "support.traveler_reply_added", entityType: "support_ticket", entityId: String(input.ticketId), metadata: { replyId: created.id } }); return { id: created.id }; }),
});
