import { CheckCircle2, FileUp, FolderOpen, Headphones, Image, MapPinned, MessageSquare, UploadCloud } from "lucide-react";
import { toast } from "sonner";
import { AdminPageFrame } from "@/components/admin/AdminPageFrame";
import { RouteMap } from "@/components/travel/RouteMap";

const tickets = [{ id: "SUP-2481", traveler: "Aarav Mehta", issue: "Airport transfer timing", status: "In progress" }, { id: "SUP-2480", traveler: "Nisha Shah", issue: "Dietary request", status: "Open" }, { id: "SUP-2478", traveler: "Kabir Rao", issue: "Ticket re-send", status: "Resolved" }];
export default function AdminOperationsPage() { return <AdminPageFrame eyebrow="FIELD GUIDE / OPERATIONS" title={<>Keep the road<br /><i>moving well.</i></>}>
  <div className="ops-field-grid"><section className="ops-map-panel"><div><span className="admin-overline">LIVE DEPARTURE / VYG-2026-08456</span><h2>South Goa route</h2><p>Day 03 · 18 travelers · Ananya Menon on ground</p></div><RouteMap /></section><section className="ops-quick-panel"><MapPinned size={20} /><h3>Operations watch</h3><p>Route status, traveler alerts, and host check-ins converge here once production location signals are connected.</p><button onClick={() => toast("Route status export prepared.")}>Export route status</button><button onClick={() => toast("Host broadcast composer opened.")}>Message trip host</button></section></div>
  <div className="ops-field-grid secondary"><section className="ops-support-panel"><div className="ops-panel-heading"><div><span className="admin-overline">SUPPORT QUEUE</span><h2>Care requests</h2></div><Headphones size={21} /></div>{tickets.map((ticket) => <button key={ticket.id} className="support-ticket-row" onClick={() => toast(`${ticket.id} detail opened.`)}><span><b>{ticket.id} · {ticket.traveler}</b><small>{ticket.issue}</small></span><em>{ticket.status}</em><MessageSquare size={15} /></button>)}</section><section className="ops-media-panel"><div className="ops-panel-heading"><div><span className="admin-overline">MEDIA & DOCUMENTS</span><h2>Route vault</h2></div><FolderOpen size={21} /></div><div className="media-folder-row"><Image size={17} /><span><b>Goa route gallery</b><small>28 optimized images</small></span><CheckCircle2 size={16} /></div><div className="media-folder-row"><FileUp size={17} /><span><b>Traveler tickets</b><small>Private PDF storage · 3 pending</small></span><button onClick={() => toast("PDF validation panel opened.")}><UploadCloud size={15} /> Upload</button></div><p className="media-validation">PDF, JPG, PNG, and WebP accepted. Production limit: 10 MB per private document.</p></section></div>
</AdminPageFrame>; }
