import { useState } from "react";
import { Banknote, CalendarRange, CircleDollarSign, FileText, MapPinned, MessageSquareText, Send, ShieldCheck, XCircle } from "lucide-react";
import { Link } from "wouter";
import { toast } from "sonner";
import { AdminPageFrame } from "@/components/admin/AdminPageFrame";
import { trpc } from "@/lib/trpc";

const value = (amount: string) => `₹${Number(amount || 0).toLocaleString("en-IN", { minimumFractionDigits: 2 })}`;

export default function AdminBookingOperationsPage({ bookingCode }: { bookingCode: string }) {
  const utils = trpc.useUtils();
  const detail = trpc.bookingLifecycle.detail.useQuery({ bookingCode }, { retry: false });
  const [adjustment, setAdjustment] = useState({ kind: "additional_charge" as "additional_charge" | "credit", description: "", amount: "", taxRate: "0" });
  const [notice, setNotice] = useState({ title: "", body: "" });
  const [update, setUpdate] = useState({ title: "", body: "" });
  const [schedule, setSchedule] = useState({ startsAt: "", endsAt: "" });
  const refresh = () => utils.bookingLifecycle.detail.invalidate({ bookingCode });
  const issueAdjustment = trpc.bookingLifecycle.issueAdjustment.useMutation({ onSuccess: () => { toast.success("Financial adjustment issued and added to the invoice."); setAdjustment({ kind: "additional_charge", description: "", amount: "", taxRate: "0" }); refresh(); }, onError: (error) => toast.error(error.message) });
  const voidAdjustment = trpc.bookingLifecycle.voidAdjustment.useMutation({ onSuccess: () => { toast.success("Adjustment voided with an invoice reversal line."); refresh(); }, onError: (error) => toast.error(error.message) });
  const reviewExtension = trpc.bookingLifecycle.reviewExtension.useMutation({ onSuccess: () => { toast.success("Extension request reviewed."); refresh(); }, onError: (error) => toast.error(error.message) });
  const reviewCancellation = trpc.bookingLifecycle.reviewCancellation.useMutation({ onSuccess: () => { toast.success("Cancellation request reviewed."); refresh(); }, onError: (error) => toast.error(error.message) });
  const reviewRefund = trpc.bookingLifecycle.reviewRefund.useMutation({ onSuccess: () => { toast.success("Refund lifecycle updated."); refresh(); }, onError: (error) => toast.error(error.message) });
  const publishUpdate = trpc.tripOps.publishUpdate.useMutation({ onSuccess: () => { toast.success("Trip update published to the verified traveler desk."); setUpdate({ title: "", body: "" }); }, onError: (error) => toast.error(error.message) });
  const queueNotice = trpc.notifications.queueTripNotice.useMutation({ onSuccess: (result) => { toast.success(result.pushQueued ? "In-app notice delivered and push queued." : "In-app notice delivered. Push will activate after device registration."); setNotice({ title: "", body: "" }); }, onError: (error) => toast.error(error.message) });

  if (detail.isLoading) return <AdminPageFrame eyebrow="BOOKINGS / OPERATIONS" title={<>Opening secure<br /><i>booking record.</i></>}><div className="admin-empty-state">Loading booking lifecycle and traveler-care actions…</div></AdminPageFrame>;
  if (!detail.data?.booking) return <AdminPageFrame eyebrow="BOOKINGS / OPERATIONS" title={<>Booking record<br /><i>unavailable.</i></>}><div className="admin-empty-state">This booking is unavailable or your role does not have operational access.</div></AdminPageFrame>;
  const { booking, adjustments, cancellations, extensions, refunds, payments } = detail.data;
  const dateForInput = (date?: Date | null) => date ? new Date(date).toISOString().slice(0, 16) : "";
  return <AdminPageFrame eyebrow="BOOKINGS / OPERATIONS" title={<>{booking.packageName}<br /><i>{booking.bookingCode}</i></>}>
    <section className="booking-ops-hero"><div><span className="admin-overline">TRAVELER BOOKING · {booking.status.toUpperCase()}</span><h2>{booking.destination}</h2><p>{booking.travelerCount} travelers · {value(String(booking.grandTotal))} current balance · {booking.startsAt && booking.endsAt ? `${new Date(booking.startsAt).toLocaleDateString()} – ${new Date(booking.endsAt).toLocaleDateString()}` : "Dates set by departure or awaiting an approved extension"}</p></div><div className="booking-ops-status"><ShieldCheck size={19} /><span>Role-bound actions<br /><b>Every update is recorded</b></span></div></section>
    <div className="booking-ops-grid">
      <section className="booking-ops-card"><div className="booking-ops-heading"><span className="admin-overline"><CircleDollarSign size={13} /> BILLING CONTROL</span><h3>Additional charges & credits</h3></div><div className="booking-adjustment-form"><select value={adjustment.kind} onChange={(event) => setAdjustment({ ...adjustment, kind: event.target.value as typeof adjustment.kind })}><option value="additional_charge">Additional charge</option><option value="credit">Credit</option></select><input value={adjustment.description} onChange={(event) => setAdjustment({ ...adjustment, description: event.target.value })} placeholder="Description" /><input value={adjustment.amount} type="number" min="1" onChange={(event) => setAdjustment({ ...adjustment, amount: event.target.value })} placeholder="Amount (INR)" /><input value={adjustment.taxRate} type="number" min="0" max="100" onChange={(event) => setAdjustment({ ...adjustment, taxRate: event.target.value })} placeholder="Tax %" /><button disabled={!adjustment.description.trim() || Number(adjustment.amount) <= 0 || issueAdjustment.isPending} onClick={() => issueAdjustment.mutate({ bookingCode, ...adjustment, amount: Number(adjustment.amount), taxRate: Number(adjustment.taxRate) })}>Issue adjustment</button></div><div className="booking-ops-list">{adjustments.length ? adjustments.map((item) => <article key={item.id}><span><b>{item.description}</b><small>{item.kind.replace("_", " ")} · {item.status}</small></span><strong>{value(String(item.amount))}</strong>{item.status !== "void" && <button onClick={() => voidAdjustment.mutate({ adjustmentId: item.id, reason: "Operator reversal" })}>Void</button>}</article>) : <p>No post-issue adjustments.</p>}</div></section>
      <section className="booking-ops-card"><div className="booking-ops-heading"><span className="admin-overline"><CalendarRange size={13} /> ITINERARY CONTROL</span><h3>Extension requests</h3></div>{extensions.length ? <div className="booking-ops-list">{extensions.map((item) => <article key={item.id} className="booking-ops-request"><span><b>{item.additionalDays} additional day{item.additionalDays === 1 ? "" : "s"}</b><small>{item.reason}</small><em>{item.status}</em></span>{item.status === "requested" && <div><input aria-label="Extension start" type="datetime-local" value={schedule.startsAt || dateForInput(item.requestedStartAt)} onChange={(event) => setSchedule({ ...schedule, startsAt: event.target.value })} /><input aria-label="Extension end" type="datetime-local" value={schedule.endsAt || dateForInput(item.requestedEndAt)} onChange={(event) => setSchedule({ ...schedule, endsAt: event.target.value })} /><button onClick={() => reviewExtension.mutate({ requestId: item.id, status: "approved", startsAt: new Date(schedule.startsAt || item.requestedStartAt || Date.now()), endsAt: new Date(schedule.endsAt || item.requestedEndAt || Date.now() + item.additionalDays * 86_400_000), operatorNote: "Approved by operations." })}>Approve dates</button><button className="quiet-danger" onClick={() => reviewExtension.mutate({ requestId: item.id, status: "rejected", operatorNote: "Unable to accommodate this requested extension." })}>Decline</button></div>}</article>)}</div> : <p className="booking-ops-empty">No route-change requests waiting for review.</p>}</section>
      <section className="booking-ops-card"><div className="booking-ops-heading"><span className="admin-overline"><XCircle size={13} /> CANCELLATION & REFUND</span><h3>Review in stages</h3></div>{cancellations.length ? <div className="booking-ops-list">{cancellations.map((item) => <article key={item.id} className="booking-ops-request"><span><b>Cancellation request</b><small>{item.reason}</small><em>{item.status}</em></span>{item.status === "requested" && <div><button onClick={() => reviewCancellation.mutate({ requestId: item.id, status: "approved", operatorNote: "Cancellation approved; refund may now be reviewed." })}>Approve cancellation</button><button className="quiet-danger" onClick={() => reviewCancellation.mutate({ requestId: item.id, status: "rejected", operatorNote: "Cancellation request declined under the applicable terms." })}>Decline</button></div>}</article>)}</div> : <p className="booking-ops-empty">No cancellation requests.</p>}<div className="refund-ledger"><b>Refund review</b>{refunds.length ? refunds.map((refund) => <div key={refund.id}><span>{value(String(refund.amount))} · {refund.status}</span>{refund.status !== "processed" && <button onClick={() => reviewRefund.mutate({ refundRequestId: refund.id, status: "approved", operatorNote: "Approved for provider settlement." })}>Approve</button>}{refund.status === "approved" && <button onClick={() => reviewRefund.mutate({ refundRequestId: refund.id, status: "processed", providerRefundId: `MANUAL-${refund.id}`, operatorNote: "Marked complete after finance confirmation." })}>Mark processed</button>}</div>) : <small>No refund request is attached to this booking.</small>}</div></section>
      <section className="booking-ops-card"><div className="booking-ops-heading"><span className="admin-overline"><MessageSquareText size={13} /> TRAVELER CARE</span><h3>Trip update & direct notice</h3></div><div className="booking-message-form"><input value={update.title} onChange={(event) => setUpdate({ ...update, title: event.target.value })} placeholder="Trip update title" /><textarea value={update.body} onChange={(event) => setUpdate({ ...update, body: event.target.value })} placeholder="Message shown in the verified trip desk" /><button disabled={update.title.length < 3 || update.body.length < 3 || publishUpdate.isPending} onClick={() => publishUpdate.mutate({ bookingId: booking.id, type: "notice", title: update.title, body: update.body, visibility: "booking", media: [] })}><MapPinned size={15} /> Publish trip update</button><input value={notice.title} onChange={(event) => setNotice({ ...notice, title: event.target.value })} placeholder="Notification title" /><textarea value={notice.body} onChange={(event) => setNotice({ ...notice, body: event.target.value })} placeholder="Short in-app or push notice" /><button disabled={notice.title.length < 3 || notice.body.length < 3 || queueNotice.isPending} onClick={() => queueNotice.mutate({ bookingCode, title: notice.title, body: notice.body, deepLink: `/trip/${bookingCode}` })}><Send size={15} /> Queue traveler notice</button></div></section>
    </div>
    <section className="booking-ops-audit"><span className="admin-overline"><Banknote size={13} /> FINANCIAL & DELIVERY CONTEXT</span><Link className="booking-ops-invoice-link" href={`/admin/invoices/${booking.bookingCode}`}><FileText size={15} /> Open invoice desk</Link><div><article><b>Invoice</b><span>{booking.invoiceNumber ?? "No issued invoice"} · {booking.invoiceStatus ?? "unavailable"} · {value(String(booking.invoiceTotal ?? 0))}</span></article><article><b>Payments</b><span>{payments.length ? payments.map((payment) => `${payment.provider} · ${payment.status} · ${value(String(payment.amount))}`).join(" | ") : "No payment records available"}</span></article><article><b>Controls</b><span>Charges add invoice lines; voiding writes a reversal line; cancellations and refunds require separate reviewed lifecycle records.</span></article></div></section>
  </AdminPageFrame>;
}
