import { Ban, CalendarDays, FileText, MessageCircle, ShieldAlert, Undo2 } from "lucide-react";
import { Link } from "wouter";
import { toast } from "sonner";
import { AdminPageFrame } from "@/components/admin/AdminPageFrame";
import { trpc } from "@/lib/trpc";

export default function AdminTravelerPage({ userId = 0 }: { userId?: number }) {
  const utils = trpc.useUtils();
  const detail = trpc.bookingLifecycle.travelerDetail.useQuery({ userId }, { retry: false, enabled: userId > 0 });
  const moderate = trpc.admin.travelers.setModerationState.useMutation({ onSuccess: () => { toast.success("Traveler account action recorded."); utils.bookingLifecycle.travelerDetail.invalidate({ userId }); }, onError: (error) => toast.error(error.message) });
  if (detail.isLoading) return <AdminPageFrame eyebrow="TRAVELERS / PROFILE" title={<>Opening traveler<br /><i>record.</i></>}><div className="admin-empty-state">Loading the connected account, booking, and support history…</div></AdminPageFrame>;
  if (!detail.data) return <AdminPageFrame eyebrow="TRAVELERS / PROFILE" title={<>Traveler record<br /><i>unavailable.</i></>}><div className="admin-empty-state">The traveler does not exist or this role cannot open the record.</div></AdminPageFrame>;
  const { traveler, bookings, supportTickets } = detail.data;
  const initials = traveler.name?.split(" ").map((part) => part[0]).join("").slice(0, 2).toUpperCase() || "TR";
  const action = (kind: "warn" | "suspend" | "ban" | "restore") => moderate.mutate({ userId, action: kind, days: kind === "suspend" ? 7 : undefined, reason: kind === "warn" ? "Administrative warning issued from the traveler record." : `${kind} action issued from the traveler record.` });
  return <AdminPageFrame eyebrow="TRAVELERS / PROFILE" title={<>{traveler.name ?? "Traveler"}<br /><i>operations record.</i></>}>
    <div className="traveler-admin-grid"><section className="traveler-profile-panel"><div className="traveler-admin-avatar">{traveler.avatarUrl ? <img src={traveler.avatarUrl} alt="" /> : initials}</div><span className="admin-overline">USER · {traveler.isBanned ? "BANNED" : traveler.isSuspended ? "SUSPENDED" : "ACTIVE"} · {traveler.role.replace("_", " ").toUpperCase()}</span><h2>{traveler.name ?? "Unnamed traveler"}</h2><p>{traveler.phone ?? "No phone on record"} · {traveler.email ?? "No email on record"}</p><div className="traveler-stat-row"><div><b>{String(bookings.length).padStart(2, "0")}</b><span>Bookings</span></div><div><b>{String(supportTickets.length).padStart(2, "0")}</b><span>Support tickets</span></div><div><b>{new Date(traveler.createdAt).getFullYear()}</b><span>Joined</span></div></div></section><section className="traveler-actions-panel"><div><span className="admin-overline">ACCOUNT CONTROLS</span><h3>Respond with care.</h3></div><Link to="/admin/engagement"><MessageCircle size={17} /> Open support queue</Link><button onClick={() => action("warn")} disabled={moderate.isPending}><ShieldAlert size={17} /> Issue warning</button><button onClick={() => action("suspend")} disabled={moderate.isPending}><CalendarDays size={17} /> Suspend for 7 days</button><button onClick={() => action("ban")} disabled={moderate.isPending}><Ban size={17} /> Ban account</button><button onClick={() => action("restore")} disabled={moderate.isPending}><Undo2 size={17} /> Restore access</button></section></div>
    <section className="traveler-admin-ledger"><h3>Journey, money, and communication record</h3>{bookings.length ? bookings.map((booking) => <Link key={booking.bookingCode} href={`/admin/bookings/${booking.bookingCode}`}><span>{booking.bookingCode} · {booking.status}</span><b>{booking.packageName} · {booking.destination} · ₹{Number(booking.grandTotal).toLocaleString("en-IN")}</b></Link>) : <p>No bookings on this traveler record.</p>}{supportTickets.length ? supportTickets.map((ticket) => <div key={ticket.ticketCode}><span>{ticket.ticketCode} · {ticket.status}</span><b>{ticket.subject} · updated {new Date(ticket.updatedAt).toLocaleDateString()}</b></div>) : <p>No support conversations on record.</p>}</section>
    <section className="traveler-admin-ledger traveler-audit-history"><h3>Secure record behavior</h3><div><span>Booking operations</span><b><FileText size={13} /> Open a booking to manage invoices, extra charges, extension requests, trip updates, cancellations, and refunds.</b></div><div><span>Account actions</span><b>Warnings, suspensions, bans, and restores are recorded with actor, target, timestamp, and reason.</b></div><p>Operational records use role-bound server actions. Individual traveler contact, bookings, and support information do not appear in public sharing or search surfaces.</p></section>
  </AdminPageFrame>;
}
